// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs8qolUAjGGtxUJqC5BwXIn9We6u51s4I',
    appId: '1:908985900149:web:71b66301833ff9f0daac3c',
    messagingSenderId: '908985900149',
    projectId: 'formula-scholar',
    authDomain: 'formula-scholar.firebaseapp.com',
    databaseURL: 'https://formula-scholar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'formula-scholar.firebasestorage.app',
    measurementId: 'G-TJ20SFY7X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI-_T9Yg9aTE7-1gHutcB8G8SHkI2GmPs',
    appId: '1:908985900149:android:3a3df19ac54bfe53daac3c',
    messagingSenderId: '908985900149',
    projectId: 'formula-scholar',
    databaseURL: 'https://formula-scholar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'formula-scholar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsgjngaMDTBceijUJGenUszLFK_3P5IqU',
    appId: '1:908985900149:ios:a4705cc9065cf60bdaac3c',
    messagingSenderId: '908985900149',
    projectId: 'formula-scholar',
    databaseURL: 'https://formula-scholar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'formula-scholar.firebasestorage.app',
    androidClientId: '908985900149-50cs5n4tv13dmjm0m0a98jnqjuse4fj2.apps.googleusercontent.com',
    iosClientId: '908985900149-3bo0aucq834g701hicf193p3avhpua3r.apps.googleusercontent.com',
    iosBundleId: 'com.glimfo.formulascholar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZpoCbJoMf_KGsgLC6k8MoEb-Pbq9EmQw',
    appId: '1:1078443290228:ios:346b963a38c2cb15516b21',
    messagingSenderId: '1078443290228',
    projectId: 'formula-scholar-prod',
    storageBucket: 'formula-scholar-prod.firebasestorage.app',
    iosBundleId: 'com.glimfo.formulascholar',
  );
}